version: '3.9'

services:
  web:
    build: .
    container_name: weather_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    restart: always